server:
  port: 8081

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujianqiang01/cloud-config-resource.git
          search-paths: '{profile}'

eureka:
  client:
    serviceUrl:
      defaultZone: http://122.51.171.168:8082/eureka/ # eureka server的地址